---
- hosts: all
  become: yes
  become_method: sudo
  
  vars:
    apache_user: www-data
    apache_group: www-data
    mysql_username: root
    mysql_password: Sep@2016

  handlers:

  - name: restart iptables
    service: name=iptables state=restarted

  - name: restart apache2
    service: name=apache2 state=restarted

  tasks: 
    - name: Workaround for requiring apt-transport-https when running apt-get update
      file:
        force: yes
        src: /usr/lib/apt/methods/http
        dest: /usr/lib/apt/methods/https
        owner: root
        group: root
        state: link
  
    - name: Install Apache HTTP Server and PHP
      apt:
        name: "{{ item }}"
        state: latest
        update_cache: yes
      with_items:
        - apache2
        - git
        - libapache2-mod-php5
        - libmysqlclient-dev
        - php5
        - php5-common
        - php5-gd
        - php5-mysql
        - php5-tidy
        - python-dev
        - python-pip
        - mysql-server
  
    # httpd.conf update necessary to address vagrant/virtualbox issue so changes to synched folder static html files work 
    #- name: Set 'EnableSendfile off' in Apache2 httpd.conf 
    #  lineinfile: dest=/etc/apache2/conf/httpd.conf regexp="^EnableSendfile off" insertafter="^#EnableSendfile " line="EnableSendfile off"
  
    - name: Copy Apache vhost config file for default ServerName
      copy:
        src: templates/etc/apache2/conf.d/servername.conf
        dest: /etc/apache2/conf-available/servername.conf
        owner: root
        group: root
        mode: 0644
  
    - name: Copy Apache vhost config file to disable Sendfile
      copy:
        src: templates/etc/apache2/conf.d/sendfile.conf
        dest: /etc/apache2/conf-available/sendfile.conf
        owner: root
        group: root
        mode: 0644

    - name: Create symlink
      file:
        src: /etc/apache2/conf-available/servername.conf
        dest: /etc/apache2/conf-enabled/servername.conf
        owner: root
        group: root
        mode: 0777
        state: link
  
    - name: Enable mod_rewrite
      apache2_module:
        name: rewrite
        ignore_configcheck: true
      notify: restart apache2
  
    - name: Copy Apache vhost config file for default web pages 
      copy:
        src: templates/etc/apache2/conf.d/000-default.conf
        dest: /etc/apache2/sites-available/000-default.conf
      notify: restart apache2
  
    - name: Create application log directory
      file:
        path: /var/log/odesurvey
        state: directory
        owner: "{{ apache_user }}"
        group: "{{ apache_group }}"
  
    - name: Set application log file permissions
      file:
        path: /var/log/odesurvey/odesurvey.log
        state: touch
        owner: "{{ apache_user }}"
        group: "{{ apache_group }}"
  
    - name: Ensure Apache running
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Install Python MySQL module
      pip:
        name: MySQL-python

    - name: Change root MySQL user password
      mysql_user:
        user: '{{ mysql_username }}'
        password: '{{ mysql_password }}'

    - name: Copy my.cnf with MySQL root credentials
      template:
        src: templates/root/.my.cnf.j2
        dest: /root/.my.cnf
        owner: root
        group: root
        mode: 0600

    - name: Restore MySQL from data dump
      mysql_db:
        name: ode_survey
        state: import
        target: /tmp/db_dump/ode_survey.sql
