---
- name: Workaround for apt-transport-https when running apt update.
  file:
    force: "yes"
    src: "/usr/lib/apt/methods/http"
    dest: "/usr/lib/apt/methods/https"
    owner: "root"
    group: "root"
    state: "link"

- name: Install system packages.
  apt:
    name: "{{ item }}"
    update_cache: "yes"
  with_items:
    - "gettext"
    - "locales"

- name: Install locales.
  locale_gen:
    name: "{{ item }}"
  with_items:
    - "de_DE"
    - "en_US"
    - "es_MX"
    - "es_ES"
    - "fr_FR"
    - "pt_BR"
